runtime: python27
api_version: 1
threadsafe: true

# runtime: python
# threadsafe: yes
#env: flex

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: matplotlib
  version: "1.2.0"
